### ISSUE TITLE
Error at ptwikis/common-iw -- <type 'exceptions.AttributeError'>

### ISSUE THREAD

**Issue by quiddity-wp** [ptwikis/ptwikis#1]
Hi :) At https://tools.wmflabs.org/ptwikis/common-iw:pt (or any input language) I'm currently getting a large error message.

Full copy&paste at https://gist.github.com/quiddity-wp/bcfd2077436b4a7f3c23d88bc9b2918f

First 10 lines:

> <type 'exceptions.AttributeError'>	Python 2.7.6: /mnt/nfs/labstore-secondary-tools-project/ptwikis/ptwikis/venv/bin/python
> Mon Nov 6 21:27:26 2017
> 
> A problem occurred in a Python script. Here is the sequence of function calls leading up to the error, in the order they occurred.
>  /mnt/nfs/labstore-secondary-tools-project/ptwikis/ptwikis/venv/local/lib/python2.7/site-packages/flup/server/fcgi_base.py in run(self=<flup.server.fcgi_base.Request object>)
>     556         """Runs the handler, flushes the streams, and ends the request."""
>     557         try:
> =>  558             protocolStatus, appStatus = self.server.handler(self)
>     559         except:
> 560 traceback.print_exc(file=self.stderr)

Screenshot: 
![image](https://user-images.githubusercontent.com/6633202/32464983-c0e5f57a-c2f6-11e7-9fed-94b5976c5920.png)

**Comment by quiddity-wp** [comment]
Update: Now the page is just responding with HTTP status 500 Internal Server Error.

**Comment by danilomac** [comment]
Fixed, there was a error with the database.
